 <Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="PublicUI\Dtos\NewFolder1\**" />
    <Compile Remove="PublicUI\Dtos\NewFolder\**" />
    <EmbeddedResource Remove="PublicUI\Dtos\NewFolder1\**" />
    <EmbeddedResource Remove="PublicUI\Dtos\NewFolder\**" />
    <None Remove="PublicUI\Dtos\NewFolder1\**" />
    <None Remove="PublicUI\Dtos\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="PublicUI\Dtos\Pages.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AS.Core\AS.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="PublicUI\Models\" />
  </ItemGroup>

</Project>
