// <auto-generated />
using System;
using AS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AS.Data.Migrations
{
    [DbContext(typeof(EfDbContext))]
    [Migration("20250129134814_ContentConfiguration_UpdateDocumentType")]
    partial class ContentConfiguration_UpdateDocumentType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AS.Entities.Entity.ActionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ActionStatus", "AS");
                });

            modelBuilder.Entity("AS.Entities.Entity.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActivityCategory")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasComment("Etkinlik Kategorisi(   Seminar = 0,  Webinar = 1,  Meeting = 2,  Workshop = 3,  Training = 4,)");

                    b.Property<DateTime>("ActivityEndDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("Etkinliğin gerçekleşme bitiş tarihi");

                    b.Property<DateTime>("ActivityStartDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("Etkinliğin gerçekleşme başlangıç tarihi");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasComment("Etkinlik Tipi (Physical = 1, Virtual = 2, Hybrid = 3,)");

                    b.Property<string>("ContentDetail")
                        .IsRequired()
                        .HasColumnType("varchar(850)")
                        .HasComment("Etkinlik İçeriği ");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Moderator")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasComment("Etkinlik Moderatörleri");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasComment("Etkinlik Poster Url");

                    b.Property<DateTime>("PublishBeginDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("Etkinliğin sitede yayına alınma başlangıç tarihi");

                    b.Property<DateTime>("PublishEndDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("Etkinliğin sitede yayından kaldırılma tarihi");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasComment("Etkinlik Sorumluları");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasComment("Etkinlik Seo Title");

                    b.Property<string>("Speakers")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasComment("Etkinlik Konuşmacıları");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(400)")
                        .HasComment("Etkinlik Başlık");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Activity", "AS", t =>
                        {
                            t.HasComment("Etkinlikler Tablosu");
                        });
                });

            modelBuilder.Entity("AS.Entities.Entity.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AnnouncementType")
                        .HasColumnType("int")
                        .HasComment("Duyuru Tipleri");

                    b.Property<string>("ContentDetail")
                        .IsRequired()
                        .HasColumnType("varchar(850)")
                        .HasComment("Duyuru İçeriği ");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("PublishBeginDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PublishEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasComment("Duyuru Seo Title");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(400)")
                        .HasComment("Duyuru Başlık");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Announcement", "AS", t =>
                        {
                            t.HasComment("Duyurular Tablosu");
                        });
                });

            modelBuilder.Entity("AS.Entities.Entity.Content", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ContentCategoryId")
                        .HasColumnType("int")
                        .HasComment("İçerik Kategorisi : News=0,       Activity=1,      Announcement=2, Slider=3");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("char(36)")
                        .HasComment("Birim Id");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UnitId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Content", "AS", t =>
                        {
                            t.HasComment("İçerik Tablosu");
                        });
                });

            modelBuilder.Entity("AS.Entities.Entity.ContentDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("ContentDocument", "AS", t =>
                        {
                            t.HasComment("İçerik Doküman Tablosu");
                        });
                });

            modelBuilder.Entity("AS.Entities.Entity.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FacultyId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Department", "AS");
                });

            modelBuilder.Entity("AS.Entities.Entity.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)");

                    b.Property<long>("DocLength")
                        .HasColumnType("bigint");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasComment("Dokümanın hangi modüle eklendiği bilgisini kategorize etmek için kullanılmıştır.");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Keyword")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("varchar(400)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Document", "AS");
                });

            modelBuilder.Entity("AS.Entities.Entity.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("EducationTime")
                        .HasMaxLength(2)
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Faculty", "AS");
                });

            modelBuilder.Entity("AS.Entities.Entity.History", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("EntityState")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("TransactionerTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TransactionerUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TransactionerUserId");

                    b.ToTable("History", "AS");
                });

            modelBuilder.Entity("AS.Entities.Entity.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(400)")
                        .HasComment("Dil Adı");

                    b.Property<string>("SeoCode")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Language", "AS", t =>
                        {
                            t.HasComment("Dil Tablosu");
                        });
                });

            modelBuilder.Entity("AS.Entities.Entity.LanguageDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("De")
                        .HasColumnType("longtext");

                    b.Property<string>("En")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Es")
                        .HasColumnType("longtext");

                    b.Property<string>("Fr")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("LanguageDefinition", "AS");
                });

            modelBuilder.Entity("AS.Entities.Entity.LogInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ControllerActionName")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionerTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TransactionerUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("LogInfo", "AS");
                });

            modelBuilder.Entity("AS.Entities.Entity.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(512)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("varchar(512)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("LanguageId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<Guid?>("PageId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Url")
                        .HasColumnType("varchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PageId")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.HasIndex("UnitId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Menus", "AS");
                });

            modelBuilder.Entity("AS.Entities.Entity.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("longtext")
                        .HasComment("Dış Url");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasComment("Tags");

                    b.Property<Guid?>("LanguageId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<int>("NewsType")
                        .HasColumnType("int")
                        .HasComment("Haber Tipleri");

                    b.Property<DateTime>("PublishBeginDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PublishEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasComment("Haber Seo Title");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("varchar(600)")
                        .HasComment("Haber Kısa Özeti ");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(400)")
                        .HasComment("Haber Başlık");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("News", "AS", t =>
                        {
                            t.HasComment("Haberler Tablosu");
                        });
                });

            modelBuilder.Entity("AS.Entities.Entity.Pages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentDetail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasComment("Tags");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("MenuId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasComment("Seo");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(400)")
                        .HasComment("Sayfa Başlık");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LanguageId");

                    b.HasIndex("MenuId")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.ToTable("Pages", "AS", t =>
                        {
                            t.HasComment("Sayfalar Tablosu");
                        });
                });

            modelBuilder.Entity("AS.Entities.Entity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<int?>("ActionStatusId")
                        .HasColumnType("int");

                    b.Property<int>("CRUDActionType")
                        .HasColumnType("int");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ActionStatusId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Permissions", "AS");
                });

            modelBuilder.Entity("AS.Entities.Entity.PermissionMenuLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MenuId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("PermissionMenuLines", "AS");
                });

            modelBuilder.Entity("AS.Entities.Entity.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdentityNo")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdateTime")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UnitId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Person", "AS");
                });

            modelBuilder.Entity("AS.Entities.Entity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Roles", "AS");
                });

            modelBuilder.Entity("AS.Entities.Entity.RolePermissionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("RolePermissionLines", "AS");
                });

            modelBuilder.Entity("AS.Entities.Entity.RoleUserLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefaultDepartment")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("RoleId");

                    b.HasIndex("UnitId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId");

                    b.ToTable("RoleUserLines", "AS");
                });

            modelBuilder.Entity("AS.Entities.Entity.Setting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Setting", "AS");
                });

            modelBuilder.Entity("AS.Entities.Entity.Slider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(700)")
                        .HasComment("Slider Açıklaması");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasComment("Slider Sıralaması");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasComment("Slider Başlık");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Slider", "AS", t =>
                        {
                            t.HasComment("Slider Tablosu");
                        });
                });

            modelBuilder.Entity("AS.Entities.Entity.Units", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(400)")
                        .HasComment("Birim Adresi");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(700)")
                        .HasComment("Birim Açıklaması");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasComment("Birim Email ");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasComment("Birim Fax");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasComment("Birim Logo 1");

                    b.Property<string>("Logo2")
                        .HasColumnType("varchar(150)")
                        .HasComment("Birim Logo 2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(400)")
                        .HasComment("Birim Adı");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(25)")
                        .HasComment("Birim Telefon");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("varchar(400)")
                        .HasComment("Birim Teması");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(350)")
                        .HasComment("Birim Url");

                    b.Property<string>("WhatshappNumber")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Units", "AS", t =>
                        {
                            t.HasComment("Birimler Tablosu");
                        });
                });

            modelBuilder.Entity("AS.Entities.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("char(128)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.Property<int>("UserType")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UK_UserEmail");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UK_UserUsername");

                    b.ToTable("Users", "AS");
                });

            modelBuilder.Entity("AS.Entities.Entity.Activity", b =>
                {
                    b.HasOne("AS.Entities.Entity.Content", "Content")
                        .WithMany("ActivityList")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("ActivityCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.Language", "Language")
                        .WithMany("ActivityList")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("ActivityUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Content");

                    b.Navigation("CreatedBy");

                    b.Navigation("Language");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AS.Entities.Entity.Announcement", b =>
                {
                    b.HasOne("AS.Entities.Entity.Content", "Content")
                        .WithMany("AnnouncementList")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("AnnouncementCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.Language", "Language")
                        .WithMany("AnnouncementList")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("AnnouncementUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Content");

                    b.Navigation("CreatedBy");

                    b.Navigation("Language");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AS.Entities.Entity.Content", b =>
                {
                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("ContentCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.Units", "Units")
                        .WithMany("Contents")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("ContentUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("Units");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AS.Entities.Entity.ContentDocument", b =>
                {
                    b.HasOne("AS.Entities.Entity.Content", "Content")
                        .WithMany("ContentDocuments")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("ContentDocumentCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.Document", "Document")
                        .WithMany("ContentDocuments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("ContentDocumentUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Content");

                    b.Navigation("CreatedBy");

                    b.Navigation("Document");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AS.Entities.Entity.Department", b =>
                {
                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("DepartmentsCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.Faculty", "Faculty")
                        .WithMany("DepartmentList")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("DepartmentsUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("Faculty");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AS.Entities.Entity.Document", b =>
                {
                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("DocumentsCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("DocumentsUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AS.Entities.Entity.Faculty", b =>
                {
                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("FacultiesCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("FacultiesUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AS.Entities.Entity.History", b =>
                {
                    b.HasOne("AS.Entities.Entity.User", "TransactionerUser")
                        .WithMany("HistoryTransactionerUser")
                        .HasForeignKey("TransactionerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TransactionerUser");
                });

            modelBuilder.Entity("AS.Entities.Entity.Language", b =>
                {
                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("LanguageCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("LanguageUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AS.Entities.Entity.LanguageDefinition", b =>
                {
                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("LanguageDefinitionCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("LanguageDefinitionUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AS.Entities.Entity.Menu", b =>
                {
                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("MenusCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.Language", "Language")
                        .WithMany("MenuList")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.Pages", "Pages")
                        .WithOne()
                        .HasForeignKey("AS.Entities.Entity.Menu", "PageId");

                    b.HasOne("AS.Entities.Entity.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AS.Entities.Entity.Units", "Units")
                        .WithMany("Menus")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("MenusUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("Language");

                    b.Navigation("Pages");

                    b.Navigation("Parent");

                    b.Navigation("Units");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AS.Entities.Entity.News", b =>
                {
                    b.HasOne("AS.Entities.Entity.Content", "Content")
                        .WithMany("NewsList")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("NewsCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.Language", "Language")
                        .WithMany("NewsList")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("NewsUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Content");

                    b.Navigation("CreatedBy");

                    b.Navigation("Language");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AS.Entities.Entity.Pages", b =>
                {
                    b.HasOne("AS.Entities.Entity.Content", "Content")
                        .WithMany("PagesList")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("PagesCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.Language", "Language")
                        .WithMany("PagesList")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.Menu", "Menu")
                        .WithOne()
                        .HasForeignKey("AS.Entities.Entity.Pages", "MenuId");

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("PagesUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Content");

                    b.Navigation("CreatedBy");

                    b.Navigation("Language");

                    b.Navigation("Menu");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AS.Entities.Entity.Permission", b =>
                {
                    b.HasOne("AS.Entities.Entity.ActionStatus", null)
                        .WithMany("PermissionLines")
                        .HasForeignKey("ActionStatusId");

                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("PermissionsCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("PermissionsUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AS.Entities.Entity.PermissionMenuLine", b =>
                {
                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("PermissionMenuLinesCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.Menu", "Menu")
                        .WithMany("PermissionMenuLines")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.Permission", "Permission")
                        .WithMany("PermissionMenuLines")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("PermissionMenuLinesUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("Menu");

                    b.Navigation("Permission");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AS.Entities.Entity.Person", b =>
                {
                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("PersonsCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.Units", "Units")
                        .WithMany("PersonList")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("PersonsUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AS.Entities.Entity.User", "User")
                        .WithOne("Person")
                        .HasForeignKey("AS.Entities.Entity.Person", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Units");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AS.Entities.Entity.Role", b =>
                {
                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("RolesCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("RolesUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AS.Entities.Entity.RolePermissionLine", b =>
                {
                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("RolePermissionLinesCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.Permission", "Permission")
                        .WithMany("RolePermissionLines")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AS.Entities.Entity.Role", "Role")
                        .WithMany("RolePermissionLines")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("RolePermissionLinesUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("Permission");

                    b.Navigation("Role");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AS.Entities.Entity.RoleUserLine", b =>
                {
                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("RoleUserLinesCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.Role", "Role")
                        .WithMany("RoleUserLines")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.Units", "Units")
                        .WithMany("RoleUserLineList")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("RoleUserLinesUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AS.Entities.Entity.User", "User")
                        .WithMany("RoleUserLines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Role");

                    b.Navigation("Units");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AS.Entities.Entity.Setting", b =>
                {
                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("SettingCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("SettingUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AS.Entities.Entity.Slider", b =>
                {
                    b.HasOne("AS.Entities.Entity.Content", "Content")
                        .WithMany("SliderList")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("SliderCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.Language", "Language")
                        .WithMany("SliderList")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("SliderUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Content");

                    b.Navigation("CreatedBy");

                    b.Navigation("Language");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AS.Entities.Entity.Units", b =>
                {
                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("UnitsCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("UnitsUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AS.Entities.Entity.User", b =>
                {
                    b.HasOne("AS.Entities.Entity.User", "CreatedBy")
                        .WithMany("UsersCreatedBy")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AS.Entities.Entity.User", "UpdatedBy")
                        .WithMany("UsersUpdatedBy")
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("AS.Entities.Entity.ActionStatus", b =>
                {
                    b.Navigation("PermissionLines");
                });

            modelBuilder.Entity("AS.Entities.Entity.Content", b =>
                {
                    b.Navigation("ActivityList");

                    b.Navigation("AnnouncementList");

                    b.Navigation("ContentDocuments");

                    b.Navigation("NewsList");

                    b.Navigation("PagesList");

                    b.Navigation("SliderList");
                });

            modelBuilder.Entity("AS.Entities.Entity.Document", b =>
                {
                    b.Navigation("ContentDocuments");
                });

            modelBuilder.Entity("AS.Entities.Entity.Faculty", b =>
                {
                    b.Navigation("DepartmentList");
                });

            modelBuilder.Entity("AS.Entities.Entity.Language", b =>
                {
                    b.Navigation("ActivityList");

                    b.Navigation("AnnouncementList");

                    b.Navigation("MenuList");

                    b.Navigation("NewsList");

                    b.Navigation("PagesList");

                    b.Navigation("SliderList");
                });

            modelBuilder.Entity("AS.Entities.Entity.Menu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("PermissionMenuLines");
                });

            modelBuilder.Entity("AS.Entities.Entity.Permission", b =>
                {
                    b.Navigation("PermissionMenuLines");

                    b.Navigation("RolePermissionLines");
                });

            modelBuilder.Entity("AS.Entities.Entity.Role", b =>
                {
                    b.Navigation("RolePermissionLines");

                    b.Navigation("RoleUserLines");
                });

            modelBuilder.Entity("AS.Entities.Entity.Units", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("Menus");

                    b.Navigation("PersonList");

                    b.Navigation("RoleUserLineList");
                });

            modelBuilder.Entity("AS.Entities.Entity.User", b =>
                {
                    b.Navigation("ActivityCreatedBy");

                    b.Navigation("ActivityUpdatedBy");

                    b.Navigation("AnnouncementCreatedBy");

                    b.Navigation("AnnouncementUpdatedBy");

                    b.Navigation("ContentCreatedBy");

                    b.Navigation("ContentDocumentCreatedBy");

                    b.Navigation("ContentDocumentUpdatedBy");

                    b.Navigation("ContentUpdatedBy");

                    b.Navigation("DepartmentsCreatedBy");

                    b.Navigation("DepartmentsUpdatedBy");

                    b.Navigation("DocumentsCreatedBy");

                    b.Navigation("DocumentsUpdatedBy");

                    b.Navigation("FacultiesCreatedBy");

                    b.Navigation("FacultiesUpdatedBy");

                    b.Navigation("HistoryTransactionerUser");

                    b.Navigation("LanguageCreatedBy");

                    b.Navigation("LanguageDefinitionCreatedBy");

                    b.Navigation("LanguageDefinitionUpdatedBy");

                    b.Navigation("LanguageUpdatedBy");

                    b.Navigation("MenusCreatedBy");

                    b.Navigation("MenusUpdatedBy");

                    b.Navigation("NewsCreatedBy");

                    b.Navigation("NewsUpdatedBy");

                    b.Navigation("PagesCreatedBy");

                    b.Navigation("PagesUpdatedBy");

                    b.Navigation("PermissionMenuLinesCreatedBy");

                    b.Navigation("PermissionMenuLinesUpdatedBy");

                    b.Navigation("PermissionsCreatedBy");

                    b.Navigation("PermissionsUpdatedBy");

                    b.Navigation("Person");

                    b.Navigation("PersonsCreatedBy");

                    b.Navigation("PersonsUpdatedBy");

                    b.Navigation("RolePermissionLinesCreatedBy");

                    b.Navigation("RolePermissionLinesUpdatedBy");

                    b.Navigation("RoleUserLines");

                    b.Navigation("RoleUserLinesCreatedBy");

                    b.Navigation("RoleUserLinesUpdatedBy");

                    b.Navigation("RolesCreatedBy");

                    b.Navigation("RolesUpdatedBy");

                    b.Navigation("SettingCreatedBy");

                    b.Navigation("SettingUpdatedBy");

                    b.Navigation("SliderCreatedBy");

                    b.Navigation("SliderUpdatedBy");

                    b.Navigation("UnitsCreatedBy");

                    b.Navigation("UnitsUpdatedBy");

                    b.Navigation("UsersCreatedBy");

                    b.Navigation("UsersUpdatedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
